- name: add boundless repos
  shell: 'echo "deb http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/third-party-debian/amd64 ./ \n deb http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/suite-test-debian/amd64 ./" >> /etc/apt/sources.list' 

- name: update repo
  apt: update_cache=yes

- name: install suite
  apt: name=suite-geoserver state=latest allow_unauthenticated=yes

- name: install gwc
  apt: name=suite-geowebcache state=latest allow_unauthenticated=yes

- name: install composer
  apt: name=suite-composer state=latest allow_unauthenticated=yes

- name: install dashboard
  apt: name=suite-dashboard state=latest allow_unauthenticated=yes

- name: install wpsbuilder
  apt: name=suite-wpsbuilder state=latest allow_unauthenticated=yes

- name: install gdal extension
  apt: name=suite-gs-gdal state=latest allow_unauthenticated=yes

- name: install gdal-mrsid
  apt: name=gdal-mrsid state=latest allow_unauthenticated=yes

- name: install extensions
  apt: name=suite-gs-{{ item }} state=latest allow_unauthenticated=yes
  with_items: 
      - appschema
      - jdbcconfig
      - cluster
      - geopkg
      - inspire
      - arcsde
      - csw
      - db2
      - gdal
      - mongodb
      - netcdf
      - oracle
      - python
      - vectortiles
      - sqlserver

- name: install netcdf extension
  apt: name=suite-gs-netcdf state=latest allow_unauthenticated=yes

- name: install wps extension
  apt: name=suite-gs-wps state=latest allow_unauthenticated=yes

- name: install netcdf native libs
  apt: name=netcdf-bin state=latest allow_unauthenticated=yes

- name: restart tomcat
  service: name=tomcat8 state=restarted

- name: install pip
  apt: name=python-pip state=latest

- name: install python dev 
  apt: name=python-dev state=latest

- name: install psycopg2 dependency
  apt: name=libpq-dev state=latest

- name: install psycopg2
  pip: name=psycopg2 state=latest

- name: install postgis
  apt: name=postgresql-9.3-postgis-2.1 state=latest allow_unauthenticated=yes

- name: update postgresql.conf
  copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: update pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: restart postgres
  service: name=postgresql state=restarted 

- name: install pointcloud
  apt: name=postgresql-9.3-pointcloud allow_unauthenticated=yes

- name: install pdal
  apt: name=pdal state=latest allow_unauthenticated=yes

- name: make data directory for tests
  file: path=/usr/share/boundless/geoserver/data-dir/data state=directory mode=777

- name: copy test data - ogr
  unarchive: src=../../test_data/cdfadmin13_1.zip dest=/usr/share/boundless/geoserver/data-dir/ mode=777

- name: copy test data - netcdf
  unarchive: src=../../test_data/netcdf.zip dest=/usr/share/boundless/geoserver/data-dir/data/ mode=777