- name: import boundless gpg key
  apt_key: url=https://apt.boundlessgeo.com/gpg.key state=present

- name: add Suite repo
  apt_repository: repo='deb https://boundless:Open4Good!@apt-ee.boundlessgeo.com/suite/latest/ubuntu/ trusty main' state=present filename='opengeo'

- name: update repo
  apt: update_cache=yes

- name: install Suite
  apt: name=opengeo state=latest

- name: install gdal extension
  apt: name=geoserver-gdal state=latest

- name: restart tomcat
  service: name=tomcat7 state=restarted

- name: install pip
  apt: name=python-pip state=latest

- name: install python dev 
  apt: name=python-dev state=latest

- name: install psycopg2 dependency
  apt: name=libpq-dev state=latest

- name: install psycopg2
  pip: name=psycopg2 state=latest

# - name: configure postgres
#   sudo: yes
#   sudo_user: postgres
#   postgresql_user: db=postgres user=postgres password=postgres

- name: update postgresql.conf
  copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: update pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: restart postgres
  service: name=postgresql state=restarted

- name: install pointcloud
  apt: name=postgresql-9.3-pointcloud

- name: install pdal
  apt: name=pdal state=latest

