- name: add boundless repos
  shell: 'echo "deb http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/third-party-debian/amd64 ./ \ndeb http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/suite-test-debian/amd64 ./" >> /etc/apt/sources.list'

- name: update repo
  apt: update_cache=yes

- name: install suite
  apt: name=suite-{{ item }} state=latest allow_unauthenticated=yes
  with_items:
      - geoserver 
      - geowebcache
      - composer
      - dashboard
      - wpsbuilder
      - docs
      - quickview

- name: install extensions
  apt: name=suite-gs-{{ item }} state=latest allow_unauthenticated=yes
  with_items: 
      - appschema
      - jdbcconfig
      - cluster
      - geopkg
      - inspire
      - arcsde
      - csw
      - db2
      - gdal
      - grib
      - mongodb
      - netcdf
      - netcdf-out
      - oracle
      - script
      - vectortiles
      - sqlserver

- name: install native libs
  apt: name={{ item }} state=latest allow_unauthenticated=yes
  with_items:
      - gdal-mrsid
      - netcdf-bin

- name: restart tomcat
  service: name=tomcat8 state=restarted

- name: install pip
  apt: name=python-pip state=latest

- name: install python dev 
  apt: name=python-dev state=latest

- name: install psycopg2 dependency
  apt: name=libpq-dev state=latest

- name: install psycopg2
  pip: name=psycopg2 state=latest

- name: install postgis
  apt: name=postgresql-9.3-postgis-2.1 state=latest allow_unauthenticated=yes

- name: update postgresql.conf
  copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: update pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: restart postgres
  service: name=postgresql state=restarted 

- name: install pointcloud
  apt: name=postgresql-9.3-pointcloud allow_unauthenticated=yes

- name: install pdal
  apt: name=pdal state=latest allow_unauthenticated=yes

- include: ../../test_data/linux_data.yml
