- name: add boundless third party repo
  apt_repository: repo="deb http://suite:B0und1e55!23@priv-repo.boundlessgeo.com/third-party-debian/amd64 ./" state=present
  
- name: add boundless test repo
  apt_repository: repo="deb http://suite:B0und1e55!23@priv-repo.boundlessgeo.com/suite-test-debian/amd64 ./" state=present

- name: update repo
  apt: update_cache=yes

- name: install suite
  # apt: name=suite-{{ item }} state=latest allow_unauthenticated=yes
  command: apt-get install -y --allow-unauthenticated suite-{{item}}
  with_items:
      - geoserver
      - geowebcache
      - composer
      - dashboard
      - wpsbuilder
      - docs
      - quickview

- name: install extensions
  command: apt-get install -y --allow-unauthenticated suite-gs-{{item}}
  # apt: name=suite-gs-{{ item }} state=latest allow_unauthenticated=yes
  with_items:
      - appschema
      - arcsde
      - cloudwatch
      - cluster
      - csw
      - db2
      - gdal
      - geopkg
      - grib
      - inspire
      - jdbcconfig
      - jdbcstore
      - jp2k
      - mbtiles
      - mongodb
      - netcdf
      - netcdf-out
      - oracle
      - script
      - sqlserver
      - vectortiles
      - wps

- name: install native libs
  # apt: name={{ item }} state=latest allow_unauthenticated=yes (requires ansible 2.1+)
  command: apt-get install -y --allow-unauthenticated {{item}}
  with_items:
      - gdal-mrsid
      - netcdf-bin

- name: restart tomcat
  service: name=tomcat8 state=restarted

- name: install pip
  apt: name=python-pip state=latest

- name: install python dev
  apt: name=python-dev state=latest

- name: install psycopg2 dependency
  apt: name=libpq-dev state=latest

- name: install psycopg2
  pip: name=psycopg2 state=latest

- name: install postgis
  command: apt-get install -y --allow-unauthenticated postgresql-9.3-postgis-2.1
  # apt: name=postgresql-9.3-postgis-2.1 state=latest allow_unauthenticated=yes (requires ansible 2.1+)

- name: update postgresql.conf
  copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: update pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/ force=yes mode=777

- name: restart postgres
  service: name=postgresql state=restarted

- name: install pointcloud
  command: apt-get install -y --allow-unauthenticated postgresql-9.3-pointcloud
  # apt: name=postgresql-9.3-pointcloud allow_unauthenticated=yes (requires ansible 2.1+)

- name: install pdal
  command: apt-get install -y --allow-unauthenticated pdal
  # apt: name=pdal state=latest allow_unauthenticated=yes (requires ansible 2.1+)

- include: ../../test_data/linux_data.yml
