- name: create directory
  file: path=~/war state=directory

- name: open port 8080
  command: netsh firewall add portopening TCP 8080 "Allow port 8080"

- name: copy install script
  copy: src=install.sh dest=~/war/install.sh force=yes mode=0700

- name: copy jce policy
  copy: src=jce_policy-8.zip dest=~/war/jce_policy-8.zip force=yes

- name: copy marlin jar
  copy: src=marlin-0.7.3-Unsafe.jar dest=~/war/marlin-0.7.3-Unsafe.jar force=yes mode=700

- name: copy apache
  copy: src=apache-tomcat-8.0.32.exe dest=~/war/apache-tomcat-8.0.32.exe mode=700

- name: copy jre
  copy: src=jre-8u73-windows-x64.exe dest=~/war/jre-8u73-windows-x64.exe mode=700

- name: copy libjpeg
  copy: src=libjpeg-turbo-1.4.2-vc64.exe dest=~/war/libjpeg-turbo-1.4.2-vc64.exe mode=700

- name: copy test data
  copy: src=test_data dest=/cygdrive/c/

- name: copy geoserver data directory
  copy: src=geoserverDataDir.zip dest=/cygdrive/c/geoserverDataDir.zip

#only run this once, if re-run will hang script
- name: run the script
  command: ./install.sh chdir=~/war

- name: copy suite war
  copy: src=OpenGeoSuiteEnterprise-latest-war.zip dest=~/

- name: unzip suite war
  unarchive: src=~/OpenGeoSuiteEnterprise-latest-war.zip dest=~/ copy=no

- name: move wars to tomcat
  shell: "cp ~/OpenGeoSuiteEnterprise-latest-war/* '/cygdrive/c/Program\ Files/Apache\ Software\ Foundation/Tomcat\ 8.0/webapps/'"

- name: stop tomcat
  command: net stop Tomcat8 
  ignore_errors: yes

- name: copy suite exts 
  copy: src=OpenGeoSuiteEnterprise-latest-ext.zip dest=~/

- name: unzip suite exts 
  command: unzip -o OpenGeoSuiteEnterprise-latest-ext.zip 

- name: explode geoserver war
  shell: "unzip -o '/cygdrive/c/Program Files/Apache Software Foundation/Tomcat 8.0/webapps/geoserver.war'"

- name: copy GDAL ext
  shell: "cp -f ~/OpenGeoSuiteEnterprise-latest-ext/gdal/* '/cygdrive/c/Program Files/Apache Software Foundation/Tomcat 8.0/webapps/geoserver/WEB-INF/lib'"

- name: copy wps ext
  shell: "cp -f ~/OpenGeoSuiteEnterprise-latest-ext/wps/* '/cygdrive/c/Program Files/Apache Software Foundation/Tomcat 8.0/webapps/geoserver/WEB-INF/lib/'"

#add some kind of wait here... if not tomcat hasn't stopped yet this fails
- name: start tomcat
  command: net start Tomcat8
