- name: create directory
  file: path=~/war state=directory

- name: create boundless dir
  file: path="/cygdrive/c/Program Files (x86)/Boundless" state=directory

- name: create suite dir
  file: path="/cygdrive/c/Program Files (x86)/Boundless/suite" state=directory

- name: create geoserver dir
  file: path="/cygdrive/c/Program Files (x86)/Boundless/suite/geoserver" state=directory

- name: create gdal dir
  file: path="/cygdrive/c/Program Files (x86)/Boundless/suite/geoserver/gdal" state=directory

- name: create marlin dir
  file: path="/cygdrive/c/Program Files (x86)/Boundless/suite/geoserver/marlin" state=directory

- name: open port 8080
  command: netsh firewall add portopening TCP 8080 "Allow port 8080"

- name: copy microsoft redist 
  copy: src=vcredist_x86.exe dest=~/ mode=777

- name: install microsoft redist
  command: ./vcredist_x86.exe /quiet

- name: copy install script
  copy: src=install.sh dest=~/war/install.sh mode=700

- name: copy jce policy
  copy: src=jce_policy-8.zip dest=~/war/jce_policy-8.zip

- name: copy apache
  copy: src=apache-tomcat-8.0.32.exe dest=~/war/  mode=700

- name: copy jre
  copy: src=jre-8u91-windows-i586.exe dest=~/war/  mode=700

- name: copy libjpeg
  copy: src=libjpeg-turbo-1.4.2-vc.exe dest=~/war/  mode=700

- name: copy netcdf
  copy: src=netCDF4.4.0-NC4-32.exe dest=~/war/ mode=700

- name: copy gdal bin
  copy: src=GDAL-suite4.9.zip dest=~/

- name: copy geoserver data directory
  copy: src=geoserverDataDir.zip dest=/cygdrive/c/

- name: unzip data dir
  unarchive: src=/cygdrive/c/geoserverDataDir.zip dest=/cygdrive/c/ mode=777 copy=no
  ignore_errors: yes

#only run this once, if re-run will hang script
- name: run the script
  command: ./install.sh chdir=~/war

- name: copy gdal files
  shell: "unzip -o GDAL-suite4.9.zip -d '/cygdrive/c/Program Files (x86)/Boundless/suite/geoserver/gdal/'"

- name: open up permissions for GDAL
  command: "chmod -R 777 /cygdrive/c/Program Files (x86)/Boundless/suite/geoserver/gdal/"

- name: get suite war
  unarchive: src=http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/war-archive/BoundlessSuite-latest-war.zip dest=~/ copy=no

- name: get suite-exts
  get_url: url=http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/war-archive/BoundlessSuite-latest-ext.zip dest=~/ 

- name: unzip suite-exts
  unarchive: src=~/BoundlessSuite-latest-ext.zip dest=~/ copy=no

- name: copy wars to tomcat webapps
  shell: "cp -f ~/BoundlessSuite-latest-war/* '/cygdrive/c/Program Files (x86)/Apache Software Foundation/Tomcat 8.0/webapps/'"

- name: stop tomcat
  command: net stop Tomcat8 
  ignore_errors: yes

- name: explode geoserver war
  shell: "unzip -o '/cygdrive/c/Program Files (x86)/Apache Software Foundation/Tomcat 8.0/webapps/geoserver.war' -d '/cygdrive/c/Program Files (x86)/Apache Software Foundation/Tomcat 8.0/webapps/geoserver'"
  args:
    executable: /bin/bash

- name: copy extensions
  shell: "cp -f -r ~/BoundlessSuite-latest-ext/{{ item }}/* '/cygdrive/c/Program Files (x86)/Apache Software Foundation/Tomcat 8.0/webapps/geoserver/WEB-INF/lib'"
  with_items: 
      - appschema
      - arcsde
      - cloudwatch
      - cluster
      - csw
      - db2
      - gdal
      - geopkg
      - grib
      - inspire
      - jdbcconfig
      - jdbcstore
      - mbtiles
      - mongodb
      - netcdf
      - netcdf-out
      - oracle
      - script
      - sqlserver
      - vectortiles
      - wps

- name: copy marlin jar
  copy: src="~/BoundlessSuite-latest-ext/marlin/" dest="/cygdrive/c/Program Files (x86)/Boundless/suite/geoserver/marlin/" remote_src=true

- name: copy GDAL jar to webapps
  copy: src="/cygdrive/c/Program Files (x86)/Boundless/suite/geoserver/gdal/gdal-1.11.2.jar" dest="/cygdrive/c/Program Files (x86)/Apache Software Foundation/Tomcat 8.0/webapps/geoserver/WEB-INF/lib/" remote_src=true

- name: ensure tomcat is stopped
  wait_for: host=0.0.0.0 port=8080 delay=10 state=stopped

- name: start tomcat
  command: net start Tomcat8

- include: ../../test_data/win_data.yml
