# main tasks for node role
- name: copy selenium server
  copy: src=selenium-server-standalone-2.52.0.jar dest=~/selenium-server-standalone-2.52.0.jar mode=777

- name: copy script
  copy: src=start_node.bat dest=/cygdrive/c/source/start_node.bat mode=777 force=yes

- name: copy node config
  copy: src=nodeConfig.json dest=~/nodeConfig.json force=yes

- name: update start_node IP
  replace:
    dest: "/cygdrive/c/source/start_node.bat"
    regexp: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'
    replace: '{{ hub_ip }}'

- name: copy ie drivers to source folder
  copy: 
    src: ~/SuiteQAAutomation/selenium/webdriver/IEDriverServer.exe
    dest: /cygdrive/c/source/
    force: yes

- name: copy Microsoft webdrivers to source folder
  copy: 
    src: ~/SuiteQAAutomation/selenium/webdriver/MicrosoftWebDriver.exe
    dest: /cygdrive/c/source/
    force: yes

- name: copy sudo script
  copy: src=sudo dest=/bin/sudo mode=777

- name: edit bashrc
  copy: src=.bashrc dest=~/.bashrc force=yes

- name: open port 8080
  command: netsh firewall add portopening TCP 8080 "Allow 8080"

- name: create start_node shortcut in startup
  command: mkshortcut -n=/cygdrive/c/Users/Administrator/AppData/Roaming/Microsoft/Windows/Start\ Menu/Programs/Startup/start_node /cygdrive/c/source/start_node.bat

- name: copy auto-logon script
  copy: src=setAutoLogon.bat dest=~/setAutoLogon.bat mode=777

# - name: run auto-logon script
#   command: sudo ./setAutoLogon.bat
