WCS100u = "ows?service=wcs&version=1.0.0&request=GetCapabilities"
WCS110 = "ows?service=wcs&version=1.1.0&request=GetCapabilities"
WCS111 = "ows?service=wcs&version=1.1.1&request=GetCapabilities"
WCS11 = "ows?service=wcs&version=1.1&request=GetCapabilities"
WCS201 = "ows?service=WCS&version=2.0.1&request=GetCapabilities"
WFS100 = "ows?service=wfs&version=1.0.0&request=GetCapabilities"
WFS110 = "ows?service=wfs&version=1.1.0&request=GetCapabilities"
WFS200 = "ows?service=wfs&version=2.0.0&request=GetCapabilities"
WMS111u = "ows?service=wms&version=1.1.1&request=GetCapabilities"
WMS130u = "ows?service=wms&version=1.3.0&request=GetCapabilities"
TMSurl = "gwc/service/tms/1.0.0"
WMSCurl = "gwc/service/wms?request=GetCapabilities&version=1.1.1&tiled=true"
WMTSurl = "gwc/service/wmts?REQUEST=GetCapabilities"

WCS100 = "WCS_Capabilities"
WCS = "Capabilities"
WFS = "WFS_Capabilities"
WMS111 = "WMT_MS_Capabilities"
WMS130 = "WMS_Capabilities"
TMS = "Tile Map Service"
WMSC = "WMT_MS_Capabilities"
WMTS = "WMT_MS_Capabilities"