<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contextpanelname</name>
   <tag></tag>
   <elementGuidId>30b3cd11-28c1-4d2b-b5a6-e6cfa1ac2903</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>context:panel:name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id58&quot;)/div[@class=&quot;tab-panel&quot;]/div[@class=&quot;selfclear clearBoth&quot;]/fieldset[@class=&quot;leftwise&quot;]/ul[1]/li[1]/input[@class=&quot;text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
