- name: Set NAT public IP in ssh.cfg
  hosts: tag_type_nat
  gather_facts: false
  vars:
    eip: "{{ hostvars[inventory_hostname]['ec2_ip_address'] }}"
  tasks:
  - name: update IP for gateway post-deploy
    local_action:
      module: lineinfile dest=~/SuiteQAAutomation/infrastructure/ansible/ssh.cfg regexp="ec2-user@" insertafter="ec2-user@" line="  ProxyCommand  ssh -W %h:%p ec2-user@{{ eip }}"

- name: provision nginx server
  hosts: tag_type_nginx
  remote_user: ubuntu
  sudo: yes
  roles:
    - nginx

- name: Setup ip forwarding on NAT
  hosts: tag_type_nat
  remote_user: ec2-user
  sudo: yes
  pre_tasks:
  - name: get nginx private ip
    sudo: no
    local_action:
      module: ec2_remote_facts
      region: us-east-1
      filters:
        "tag:Name": QA nginx
    register: nginx_facts
  - name: get nginx private ip
    sudo: no
    local_action:
      module: ec2_remote_facts
      region: us-east-1
      filters:
        "tag:Name": QA Win10 Node
    register: win10_facts
  - name: get ubuntu_gs private ip
    sudo: no
    local_action:
      module: ec2_remote_facts
      region: us-east-1
      filters:
        "tag:Name":  QA Ubuntu gs
    register: ubuntu_gs_facts
  vars:
    nat_ip: "{{ hostvars[inventory_hostname]['ec2_private_ip_address'] }}"
    nginx_ip: "{{ nginx_facts.instances[0].private_ip_address }}"
    win10_ip: "{{ win10_facts.instances[0].private_ip_address }}"
    ubuntu_gs_ip: "{{ ubuntu_gs_facts.instances[0].private_ip_address }}"

  roles:
    - nat

- name: Provision dependencies on hub instance
  hosts: tag_type_hub
  remote_user: ec2-user
  sudo: yes
  vars: 
    hub_ip: "{{ hostvars[inventory_hostname]['ec2_private_ip_address'] }}"
  roles:
    - hub

- name: provision win10 node
  hosts: tag_type_win10
  remote_user: Administrator
  pre_tasks:
  - name: get hub private ip
    sudo: no
    local_action:
      module: ec2_remote_facts
      region: us-east-1
      filters:
        "tag:Name": QA Grid Hub
    register: hub_facts
  vars:
    hub_ip: "{{ hub_facts.instances[0].private_ip_address }}"
    node_id: "{{ hostvars[inventory_hostname]['ec2_id'] }}"
  roles:
    - win_node
  post_tasks:
  - name: restart win_node to activate autologon
    sudo: no
    command: shutdown /r
    async: 0
    poll: 0
    ignore_errors: true


- name: provision win2012 node
  hosts: tag_type_win2012
  remote_user: Administrator
  roles:
    - win_2012

- name: provision ubuntu GS machine
  hosts: tag_type_ubuntu_gs
  remote_user: ubuntu
  sudo: yes
  roles:
    - ubuntu_gs

- name: provision centos GS machine
  hosts: tag_type_centos_gs
  remote_user: centos
  sudo: yes
  roles:
    - centos
