- name: Setup ip forwarding on NAT
  hosts: gateway
  remote_user: ec2-user
  sudo: yes
  roles:
    - nat

- name: Provision dependencies on hub instance
  hosts: tag_type_hub
  remote_user: ec2-user
  sudo: yes
  roles:
    - hub

- name: provision nginx server
  hosts: tag_type_nginx
  remote_user: ubuntu
  sudo: yes
  roles:
    - nginx

- name: provision win10 node
  hosts: tag_type_win10
  remote_user: Administrator
  roles:
    - win_node

- name: provision win2012 node
  hosts: tag_type_win2012
  remote_user: Administrator
  roles:
    - win2012_node


