#setup IP file on nginx when install.yml run or deploy? or here??
# - on install put on hub, when install.yml is run

- name: generate hub key for hub -> nginx
  hosts: tag_type_hub
  remote_user: ec2-user
  sudo: yes
  tasks:
    - include: roles/hub/tasks/gen_hub_key.yml

- name: generate nginx key for nginx -> hub
  hosts: tag_type_nginx
  remote_user: ubuntu
  sudo: yes
  tasks:
    - include: roles/nginx/tasks/gen_nginx_key.yml

- name: fetch nginx pub key
  hosts: tag_type_hub
  remote_user: ec2-user
  sudo: yes
  tasks:
    - include: roles/hub/tasks/retrieve_nginx_key.yml

- name: fetch hub pub key
  hosts: tag_type_nginx
  remote_user: ubuntu
  sudo: yes
  tasks:
    - include: roles/nginx/tasks/retrieve_hub_key.yml

