### !!!ENSURE --tag_type_targetinstance is used when running this play or all machines will be terminated!!!! ####
- hosts: tag_type_win2012
  remote_user: Administrator
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: windows_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate windows win2012
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: tag_type_win10
  remote_user: Administrator
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: windows_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate windows_10
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: tag_type_hub
  gather_facts: True
  remote_user: ec2-user
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: linux_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate hub
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: tag_type_ubuntu_gs
  gather_facts: True
  remote_user: ubuntu
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: linux_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate ubuntu_gs
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: tag_type_centos_gs
  gather_facts: True
  remote_user: centos
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: linux_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate centos_gs
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: tag_type_nginx
  gather_facts: True
  remote_user: ubuntu
  vars:
    - region: 'us-east-1'
  tasks:
    - name: gather ec2-facts
      action: ec2_facts
      register: nginx_facts
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: terminate nginx machine
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

- hosts: geoservers
  gather_facts: false
  tasks:
  - name: stop all instances running geoserver
    local_action:
      module: ec2
      state: 'absent'
      region: us-east-1
      instance_ids: "{{ hostvars[inventory_hostname]['ec2_id'] }}"

- hosts: selenium hosts
  gather_facts: false
  tasks:
  - name: terminate the selenium grid hub (ec2-linux) and node (win10) instances
    local_action:
      module: ec2
      state: 'absent'
      region: us-east-1
      instance_ids: "{{ hostvars[inventory_hostname]['ec2_id'] }}"

# #remove NAT 
# - hosts: tag_type_nat
#   gather_facts: True
#   remote_user: ec2-user
#   vars:
#     - region: 'us-east-1'
#   tasks:
#     - name: gather ec2-facts
#       action: ec2_facts
#       register: linux_facts
#     - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

#     - name: terminate nat
#       local_action:
#         module: ec2
#         state: 'absent'
#         region: us-east-1
#         instance_ids: "{{ ansible_ec2_instance_id }}"
