### Install robot
- name: Install Robot Framework
  pip: name={{ item }} state=latest
  with_items:
    - robotframework
    - robotframework-httplibrary
    - robotframework-databaselibrary

- name: Install RF Selenium2 library
  pip: name=robotframework-selenium2library state=present version=1.7.4

# patch selenium library
- name: Patch Selenium2 Library for Edge
  copy:
    remote_src: True
    src: /home/ec2-user/robot/robot_sel2_patch/_browsermanagement.py
    dest: /usr/local/lib/python2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py

- name: unininstall pil library
  pip: name=pil state=absent

- name: install gcc
  yum: name=gcc state=latest

- name: install Pillow dependencies
  yum: name={{ item }} state=latest
  with_items:
    - libtiff-devel
    - libjpeg-devel
    - libzip-devel
    - freetype-devel
    - lcms2-devel
    - libwebp-devel
    - tcl-devel

- name: install pillow
  pip: name=Pillow state=latest

- name: install postgres
  yum: name=postgresql-devel state=latest

- name: install psycopg2
  pip: name=psycopg2 state=latest

### Install docker-py required for Docker module
- name: install docker-py
  pip: name=docker-py

### Install and start Docker
- name: Install Docker
  yum: name=docker state=latest

- name: start docker
  service: name=docker  state=started

### pull and start selenium hub image
- name: Selenium Grid Hub container
  docker:
    name: selenium-hub
    image: selenium/hub:latest
    ports: 4444:4444
    state: reloaded
    pull: missing

### get suite-war.zip and suite-exts.zip

- name: install subversion
  yum: name=subversion state=latest

### get robot tests and test data
- name: Retrieve test files from git
  subversion: repo=https://github.com/boundlessgeo/SuiteQAAutomation/trunk/robot/ dest=/home/ec2-user/robot export=yes force=yes username=boundlessQA password=QA4Good!

- name: give Robot folder RW permissions
  command: chmod -R 777 robot/

- name: copy test data
  copy: src=test_data dest=/home/ec2-user/

