<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Services</name>
   <tag></tag>
   <elementGuidId>0c8a1b5d-1b6f-42f6-8e3f-862b8a125c24</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation&quot;)/li[@class=&quot;navigation-tab&quot;]/ul[@class=&quot;navigation-tab-content plain&quot;]/li[@class=&quot;nav-administer-service&quot;]/a[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
