<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select2-selection__arrow</name>
   <tag></tag>
   <elementGuidId>09344ec2-cb69-411e-b699-f3f26a3ed13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#id5b > div.tab-panel > div > fieldset.leftwise > div > fieldset > ul > li:nth-child(2) > span > span.selection > span > span.select2-selection__arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id5b&quot;)/div[@class=&quot;tab-panel&quot;]/div[@class=&quot;selfclear clearBoth&quot;]/fieldset[@class=&quot;leftwise&quot;]/div[1]/fieldset[1]/ul[1]/li[2]/span[@class=&quot;select2 select2-container select2-container--default select2-container--open select2-container--above&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]/span[@class=&quot;select2-selection__arrow&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#id5b > div.tab-panel > div > fieldset.leftwise > div > fieldset > ul > li:nth-child(2) > span > span.selection > span > span.select2-selection__arrow</value>
   </webElementProperties>
</WebElementEntity>
