# hosts
[localhost]
localhost   ansible_connection=local  ansible_python_interpreter="/usr/local/bin/pip"

[tag_type_hub]

[tag_type_nat]

[tag_type_nginx]

[tag_type_win10]

[tag_type_win2012]

[linux_boxes:children]
tag_type_nginx
tag_type_nat
tag_type_hub

[win_boxes:children]
tag_type_win2012
tag_type_win10
