# Main task file for nginx server role
- name: install nginx
  apt: name=nginx update_cache=yes state=present

- name: install apache2-utils
  apt: name=apache2-utils state=present

- name: create password file
  command: htpasswd -cb /etc/nginx/.htpasswd boundless Open4Test!

- name: create default site config
  copy: src=nginx.conf dest=/etc/nginx/sites-available/default

- name: install svn
  apt: name=subversion state=latest

- name: get basic website files
  subversion: repo=https://github.com/boundlessgeo/SuiteQAAutomation/trunk/robot/reports force=yes export=yes username=boundlessQA password=QA4Good! dest=/usr/share/nginx/html

- name: restart nginx
  service: name=nginx state=restarted
