- name: set boundless repo
  command: bash -c 'printf "[boundless-third-party]\nname=Boundless Spatial Third Party Repo\nbaseurl=http://suite:B0und1e55!23@priv-repo.boundlessgeo.com/third-party-centos\nenabled=1\ngpgcheck=0" | sudo tee /etc/yum.repos.d/boundless-third-party.repo'

- name: add suite test repo
  command: bash -c 'printf "[boundless-suite-test-centos]\nname=Boundless Spatial Suite Test CentOS\nbaseurl=http://suite:B0und1e55!23@priv-repo.boundlessgeo.com/suite-test-centos/\nenabled=1\ngpgcheck=0" | sudo tee /etc/yum.repos.d/boundless-suite-test.repo'

- name: insall suite
  yum: name=suite-{{ item }} state=latest
  with_items:
      - geoserver
      - composer
      - geowebcache
      - dashboard
      - wpsbuilder
      - docs
      - quickview

- name: install extensions
  yum: name=suite-gs-{{ item }} state=latest
  with_items:
      - appschema
      - arcsde
      - cloudwatch
      - cluster
      - csw
      - db2
      - gdal
      - geopkg
      - grib
      - inspire
      - jdbcconfig
      - jdbcstore
      - jp2k
      - mbtiles
      - mongodb
      - netcdf
      - netcdf-out
      - oracle
      - script
      - sqlserver
      - vectortiles
      - wps

- name: install native libs
  yum: name={{ item }} state=latest
  with_items:
      - netcdf
      - gdal-mrsid
      - libjpeg-turbo

- name: add libjpeg to tomcat conf
  command: echo "JAVA_OPTS=\"-DJjava.library.path=/opt/libjpeg-turbo/lib64\"" >> /etc/tomcat8/tomcat8.conf

- name: start tomcat8
  service: name=tomcat8 state=restarted

- name: install postgis
  yum: name=postgis21-postgresql93 state=present

- name: init postgis
  command: service postgresql-9.3 initdb

- name: install pointcloud
  yum: name=pointcloud-postgresql93.x86_64 state=present

- name: update postgresql.conf
  copy: src=postgresql.conf dest=/var/lib/pgsql/9.3/data/ force=yes mode=777

- name: update pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data/ force=yes mode=777

- name: restart postgis
  service: name=postgresql-9.3 state=started

- name: turn off iptables
  command: chkconfig iptables off

- name: stop iptables service
  service: name=iptables state=stopped

- name: set permissive
  command: setenforce permissive

- name: set sysconfig permissive
  command: sed -i "s/SELINUX-enforcing/SELINUX=permissive/" /etc/sysconfig/selinux

- include: ../../test_data/linux_data.yml
