- name: set boundless repo
  command: bash -c 'printf "[boundless-third-party]\nname=Boundless Spatial Third Party Repo\nbaseurl=http://yum.boundlessgeo.com/third-party/\nenabled=1\ngpgcheck=0" | sudo tee /etc/yum.repos.d/boundless-third-party.repo'

- name: add suite test repo
  command: bash -c 'printf "[boundless-suite-test-centos]\nname=Boundless Spatial Suite Test CentOS\nbaseurl=http://jenkins:Thae9suv@priv-repo.boundlessgeo.com/suite-test-centos/\nenabled=1\ngpgcheck=0" | sudo tee /etc/yum.repos.d/boundless-suite-test.repo'

- name: insall suite geoserver
  yum: name=suite-geoserver state=present

- name: install composer
  yum: name=suite-composer state=present

- name: install dashboard
  yum: name=suite-dashboard state=present

- name: install wps builder
  yum: name=suite-wpsbuilder state=present

- name: install gdal extension
  yum: name=suite-gs-gdal state=present

- name: install netcdf extension
  yum: name=suite-gs-netcdf state=present

- name: install netcdf native libs
  yum: name=netcdf-bin state=present

- name: install gdal mrsid 
  yum: name=gdal-mrsid state=present

- name: unzip to jre lib
 unarchive: src=http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip dest=/usr/lib/jvm/jre/lib/security/ copy=no

- name: add libjpeg to tomcat conf
  command: echo "JAVA_OPTS=\"-DJjava.library.path=/opt/libjpeg-turbo/lib64\"" >> /etc/tomcat8/tomcat8.conf

- name: start tomcat8
  service: name=tomcat8 state=restarted

- name: install postgis
  yum: name=postgis21-postgresql93.x86_64 state=present

#required for postgis, libjpeg-turbo-official not enough
- name: install libjpeg-turbo
  yum: name=libjpeg-turbo.x86_64 state=present

- name: init postgis
  command: service postgresql-9.3 initdb

- name: install pointcloud
  yum: name=pointcloud-postgresql93.x86_64 state=present

- name: update postgresql.conf
  copy: src=postgresql.conf dest=/var/lib/pgsql/9.3/data/ force=yes mode=777

- name: update pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data/ force=yes mode=777

- name: restart postgis
  service: name=postgresql-9.3 state=started

- name: turn off iptables
  command: chkconfig iptables off

- name: stop iptables service
  service: name=iptables state=stopped

- name: set permissive
  command: setenforce permissive

- name: set sysconfig permissive
  command: sed -i "s/SELINUX-enforcing/SELINUX=permissive/" /etc/sysconfig/selinux

- name: make data directory for tests
  file: path=/usr/share/boundless/geoserver/data-dir/data state=directory mode=777

- name: copy test data - ogr
  unarchive: src=../../test_data/cdfadmin13_1.zip dest=/usr/share/boundless/geoserver/data-dir/ mode=777

- name: copy test data - netcdf
  unarchive: src=../../test_data/netcdf.zip dest=/usr/share/boundless/geoserver/data-dir/data/ mode=777
