<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OK0</name>
   <tag></tag>
   <elementGuidId>0d2acc14-9c02-4bae-83e0-3f0d25c58598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html body div#_wicket_window_0.wicket-modal form div#_wicket_window_1.w_blue div#_wicket_window_7.w_left div.w_right_1 div#_wicket_window_8.w_right div.w_content_1 div.w_content_2 div.w_content_3 div.w_content div#_wicket_window_3.w_content_container div#id5f div#id60 div.button-group.rightwise a#id61</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id68</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id68&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>html body div#_wicket_window_0.wicket-modal form div#_wicket_window_1.w_blue div#_wicket_window_7.w_left div.w_right_1 div#_wicket_window_8.w_right div.w_content_1 div.w_content_2 div.w_content_3 div.w_content div#_wicket_window_3.w_content_container div#id5f div#id60 div.button-group.rightwise a#id61</value>
   </webElementProperties>
</WebElementEntity>
